### PR TITLE
Allow react 16 as peerDependency

### PR DESCRIPTION
**Pull request by okize**
Add `prop-types` & `create-react-class` packages to make the minimum amount of changes to be compatible with React 16.

### CODE REVIEW

**Comment by benbriggs** [comment]
👍  thanks! i'm going to follow up with a migration of the example files to 16 as well.

**Comment by benbriggs** [comment]
I'm going to open up an issue to switch bundled components to ES6 classes so that we don't need the `create-react-class` dependency long term (even though i prefer the original factory function style 😢 )

**Comment by benbriggs** [comment]
@okize landed in 1.5.2

**Comment by okize** [comment]
thanks @benbriggs !!

**Pull request merged**
